PsplGenericSystem/Extensions/HRMS.Web/Controllers/PayPeriodController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HRMS.Service.Models.EDM;
using HRMS.Web.Helper;
using HRMS.Web.Areas.HireWizard.Models;
using HRMS.Service.Interfaces;
using HRMS.Web.ViewModels;

namespace HRMS.Web.Controllers
{
    public class PayPeriodController : Controller
    {

        #region Class Level Variables and constructor

        private readonly IPayPeriodRepository _payPeriodRepository;
        private readonly IPayPeriodTypeRepository _payPeriodTypeRepository;

        public PayPeriodController(IPayPeriodRepository payPeriodRepository, IPayPeriodTypeRepository payPeriodTypeRepository)
        {
            _payPeriodRepository = payPeriodRepository;
            _payPeriodTypeRepository = payPeriodTypeRepository;
        }

        protected IPayPeriodRepository PayPeriodRepository
        {
            get { return _payPeriodRepository; }
        }

        protected IPayPeriodTypeRepository PayPeriodTypeRepository
        {
            get { return _payPeriodTypeRepository; }
        }

        #endregion



        /// <summary>
        /// Returns PayPeriod List by CompanyId
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [ActionName("SelectAllPayPeriodDetails")]
        public ActionResult SelectAllPayPeriodDetails()
        {
            List<PayPeriodType> payperiodtypeobj = new List<PayPeriodType>();
            payperiodtypeobj = _payPeriodTypeRepository.SelectAllPayPeriodTypeDetails(Convert.ToInt32(GlobalsVariables.CurrentCompanyId)).ToList();

            var payperiodList = _payPeriodRepository.SelectAllPayPeriodDetails(Convert.ToInt32(GlobalsVariables.CurrentCompanyId));

            for (int i = 0; i < payperiodList.Count; i++)
            {
                payperiodList[i].PayPeriodTypename = payperiodtypeobj.Where(pt => pt.PayPeriodTypeId == payperiodList[i].PayPeriodTypeId).Select(pt => pt.Name).SingleOrDefault();
                payperiodList[i].PayPeriodDays = (payperiodtypeobj.Where(pt => pt.PayPeriodTypeId == payperiodList[i].PayPeriodTypeId).Select(pt => pt.Days).SingleOrDefault()).GetValueOrDefault();
            }

            PayPeriodFormModel payPeriodFormModelObj = new PayPeriodFormModel();
            payPeriodFormModelObj.PayPeriodList = payperiodList;
            payPeriodFormModelObj.PayPeriodTypeList = payperiodtypeobj;

            return View(payPeriodFormModelObj);
        }


        /// <summary>
        /// AddPayPeriodDetail - Get Method: Returns the PayPeriodDetails View.
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [ActionName("AddPayPeriodDetail")]
        public ActionResult AddPayPeriodDetail()
        {
            var payperiodFormModelObj = new PayPeriodFormModel
            {
                PayPeriodTypeList = _payPeriodTypeRepository.SelectAllPayPeriodTypeDetails(Convert.ToInt32(GlobalsVariables.CurrentCompanyId))
            };
            //payperiodFormModelObj.PayPeriod.NextSchedule

            return View(payperiodFormModelObj);
        }

        [HttpGet]
        [ActionName("GetPayPeriodDays")]
        public JsonResult GetPayPeriodDays(string PayPeriodTypeId)
        {
            var model = _payPeriodTypeRepository.SelectPayPeriodTypeDetails(Convert.ToInt32(PayPeriodTypeId), Convert.ToInt32(GlobalsVariables.CurrentCompanyId));
            return Json(model, JsonRequestBehavior.AllowGet);
        }


        /// <summary>
        /// AddPayPeriodDetail - Post Method: Inserts New PayPeriod.
        /// </summary>
        /// <param name="payperiodItem"></param>
        /// <returns></returns>
        [HttpPost]
        [ActionName("AddPayPeriodDetail")]
        public ActionResult AddPayPeriodDetail(PayPeriodFormModel payperiodFormItem)
        {
            bool success = false;
            if (ModelState.IsValid)
            {
                payperiodFormItem.PayPeriod.CompanyId = Convert.ToInt32(GlobalsVariables.CurrentCompanyId);
                success = _payPeriodRepository.InsertPayPeriod(payperiodFormItem.PayPeriod);
            }

            if (success)
                return RedirectToAction("SelectAllPayPeriodDetails");
            return View();
        }


        /// <summary>
        /// EditPayPeriodDetail - Get Method: Returns the EditPayPeriod View.
        /// </summary>
        /// <param name="PayPeriodId"></param>
        /// <returns></returns>
        [HttpGet]
        [ActionName("EditPayPeriodDetail")]
        public ActionResult EditPayPeriodDetail(int PayPeriodId)
        {
            PayPeriods payperiodDetail = new PayPeriods();

            payperiodDetail = _payPeriodRepository.SelectPayPeriodDetail(PayPeriodId, Convert.ToInt32(GlobalsVariables.CurrentCompanyId)).SingleOrDefault();

            List<PayPeriodType> PayPeriodTypeObj = _payPeriodTypeRepository.SelectAllPayPeriodTypeDetails(Convert.ToInt32(GlobalsVariables.CurrentCompanyId));

            payperiodDetail.PayPeriodDays = (PayPeriodTypeObj.Where(pt => pt.PayPeriodTypeId == payperiodDetail.PayPeriodTypeId).Select(pt => pt.Days).SingleOrDefault()).GetValueOrDefault();
          
            PayPeriodFormModel payPeriodFormModel = new PayPeriodFormModel();

            payPeriodFormModel.PayPeriod = payperiodDetail;
            payPeriodFormModel.PayPeriodTypeList = PayPeriodTypeObj;

            return View(payPeriodFormModel);
        }


        /// <summary>
        /// EditPayPeriod - Post Method: Updates the PayPeriod Information.
        /// </summary>
        /// <param name="payperiodItem"></param>
        /// <returns></returns>
        [HttpPost]
        [ActionName("EditPayPeriodDetail")]
        public ActionResult EditPayPeriodDetail(PayPeriodFormModel payperiodFormItem)
        {
            bool success = false;

            if (ModelState.IsValid)
            {
                success = _payPeriodRepository.UpdatePayPeriod(payperiodFormItem.PayPeriod);
            }

            if (success)
                return RedirectToAction("SelectAllPayPeriodDetails");
            return View();
        }


        /// <summary>
        /// DeletePayPeriod - Post Method: Deletes the PayPeriod Information.
        /// </summary>
        /// <param name="PayPeriodIds"></param>
        /// <returns></returns>
        [HttpPost]
        [ActionName("DeletePayPeriodDetail")]
        public bool DeletePayPeriodDetail(string PayPeriodIds)
        {

            if (PayPeriodIds != null)
            {
                foreach (var PayPeriodId in PayPeriodIds.Split(','))
                {
                    var deletePayPeriodDetail =
                         _payPeriodRepository.DeletePayPeriodDetail(Int32.Parse(PayPeriodId), Convert.ToInt32(GlobalsVariables.CurrentCompanyId));
                }
            }
            return true;
        }
    }
}

PsplGenericSystem/Extensions/HRMS.Web/Views/PayPeriod/AddPayPeriodDetail.cshtml
@model @HRMS.Web.ViewModels.PayPeriodFormModel
@using System.Web.Optimization;
@using HRMS.Web.Helper;
@{
    ViewBag.Title = "AddPayPeriodDetail";
    Layout = "~/Views/Shared/_MasterLayout.cshtml";
}
<script src="~/Scripts/HRMS.TIME.Plugins.js"></script>
<html>
<body>

    @using (Html.BeginForm("AddPayPeriodDetail", "PayPeriod", FormMethod.Post))
    {
        @Html.ValidationSummary(true)

        <div class="form-horizontal">
            <div class="form-group">
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(m => m.PayPeriod.PayPeriodDescription, new { @class = "col-sm-4 control-label required" })
                        <div class="col-sm-8">
                            @Html.TextBoxFor(m => m.PayPeriod.PayPeriodDescription, new { @class = "form-control", placeholder = "Description" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.PayPeriod.PayPeriodTypeId, new { @class = "col-sm-4 control-label required" })
                        <div class="col-sm-8">
                            @Html.DropDownListFor(m => m.PayPeriod.PayPeriodTypeId, new SelectList(Model.PayPeriodTypeList, "PayPeriodTypeId", "Name"), "--Select--", new Dictionary<string, Object> { { "class", "form-control" }, { "data-val-1", "Days" }, { "id", "dpPayPeriodType" } })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.PayPeriod.PayPeriodDays, new { @class = "col-sm-4 control-label " })
                        <div class="col-sm-8">
                            @Html.TextBoxFor(m => m.PayPeriod.PayPeriodDays, new { @readonly = "readonly", @class = "form-control", id = "txtpayperioddays", placeholder = "PayPeriod Days" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.PayPeriod.StartDateTime, new { @class = "col-sm-4 control-label  required" })
                        <div class="col-sm-8">
                            <div class="input-group">
                                @Html.TextBoxFor(m => m.PayPeriod.StartDateTime,new { @onchange = "setPeriodEndValues()", @class = "form-control dateControl", @id = "txtStartDateTime" })
                                <label for="txtStartDateTime" class="input-group-addon btn">
                                    <span class="glyphicon glyphicon-calendar"></span>
                                </label>
                            </div>

                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.PayPeriod.EndDateTime, new { @class = "col-sm-4 control-label " })
                        <div class="col-sm-8">
                            <div class="input-group">
                                @* @Html.TextBoxFor(m => m.EndDateTime, (Model.EndDateTime == null ? "" : ((DateTime)Model.EndDateTime).ToString("MM/dd/yyyy")), new { @class = "form-control dateControl", @maxlength = "10"})*@
                                @Html.TextBoxFor(m => m.PayPeriod.EndDateTime,  new { @readonly = "readonly", @class = "form-control dateControl", @id = "txtEndDateTime" })
                                <label for="txtEndDateTime" class="input-group-addon btn">
                                    <span class="glyphicon glyphicon-calendar"></span>
                                </label>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(m => m.PayPeriod.PayPeriodCheckDate, new { @class = "col-sm-4 control-label " })
                        <div class="col-sm-8">
                            <div class="input-group">
                                @* @Html.TextBoxFor(m => m.EndDateTime, (Model.EndDateTime == null ? "" : ((DateTime)Model.EndDateTime).ToString("MM/dd/yyyy")), new { @class = "form-control dateControl", @maxlength = "10"})*@
                                @Html.TextBoxFor(m => m.PayPeriod.PayPeriodCheckDate, new { @readonly = "readonly", @class = "form-control dateControl", @id = "txtPaycheckDateTime" })
                                <label for="txtPaycheckDateTime" class="input-group-addon btn">
                                    <span class="glyphicon glyphicon-calendar"></span>
                                </label>
                            </div>
                        </div>
                    </div>


                    <div class="form-group">
                        @Html.LabelFor(m => m.PayPeriod.StartDayOfWeek, new { @class = "col-sm-4 control-label required" })
                        <div class="col-sm-8">
                            @Html.TextBoxFor(m => m.PayPeriod.StartDayOfWeek, new { @class = "form-control", id = "txtStartDay", placeholder = "Start Day Of Week" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.PayPeriod.NextSchedule, new { @class = "col-sm-4 control-label " })
                        <div class="col-sm-8">
                            @Html.CheckBoxFor(m => m.PayPeriod.NextSchedule, new { @class = "form-control", id = "chkNextSchedule", placeholder = "Builds next schedule on closing the Pay Period" })
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 control-button">
                
                @Html.ActionLink("Cancel", "SelectAllPayPeriodDetails", "PayPeriod", new { @CompanyId = GlobalsVariables.CurrentCompanyId }, new { @class = "btn btn-success" })
                <button type="submit" id="btnsubmit" class="btn btn-success">Save</button>
            </div>
        </div>

    }

    <script type="text/javascript">
        $(document).ready(function () {
            var resultingSiteview = "<h1>PayPeriod <small>Add PayPeriod </small></h1><ol class=" + '"breadcrumb"' + "><li><a href=" + '"../Home/EmployeeDashboard"' + "><i class=" + '"fa fa-dashboard"' + "></i>Home</a></li><li class=" + '"active"' + ">PayPeriod</li></ol>";
            $("#header-section").empty();
            $("#header-section").html(resultingSiteview);
        });
    </script>

    <script type="text/javascript">
        $(document).ready(function () {
            $("#dpPayPeriodType").change(function () {
            
                var payperiodTypeIdVal = $(this).val();
                if (payperiodTypeIdVal) {
                    var baseurl = '@System.Configuration.ConfigurationManager.AppSettings["BaseURL"]';
                    baseurl += "PayPeriod/GetPayPeriodDays";
                    $.getJSON(baseurl, { PayPeriodTypeId: payperiodTypeIdVal }, function (payperiodTypeData) {
                     
                        $("#txtpayperioddays").val(payperiodTypeData[0].Days);
                        setPeriodEndValues();
                    });
                }
            });

        });


        function setPeriodEndValues() {
         
            if (validateNullValue('txtStartDateTime')) {
                var periodDays = $("#txtpayperioddays").val();
                var startDate = new Date($("#txtStartDateTime").val());
                var periodEndDate = new Date(startDate);
                periodEndDate.setDate(periodEndDate.getDate() + parseInt(periodDays - 1));
                $("#txtEndDateTime").val((periodEndDate.getMonth() + 1) + "/" + periodEndDate.getDate() + "/" + periodEndDate.getFullYear());
                $("#txtPaycheckDateTime").val((periodEndDate.getMonth() + 1) + "/" + periodEndDate.getDate() + "/" + periodEndDate.getFullYear());
                
                var dayOfWeek = new Date($("#txtStartDateTime").val()).getDay();
                switch (dayOfWeek) {
                    case 0:
                        $("#txtStartDay").val("Sunday");
                        break;
                    case 1:
                        $("#txtStartDay").val("Monday");
                        break;
                    case 2:
                        $("#txtStartDay").val("Tuesday");
                        break;
                    case 3:
                        $("#txtStartDay").val("Wednesday");
                        break;
                    case 4:
                        $("#txtStartDay").val("Thursday");
                        break;
                    case 5:
                        $("#txtStartDay").val("Friday");
                        break;
                    case 6:
                        $("#txtStartDay").val("Saturday");
                        break;
                }
            }
        }
    </script>
</body>
</html>

PsplGenericSystem/Extensions/HRMS.Web/Views/PayPeriod/EditPayPeriodDetail.cshtml
@model @HRMS.Web.ViewModels.PayPeriodFormModel
@using System.Web.Optimization;
@using HRMS.Data;
@using HRMS.Web.Helper;
@{
    ViewBag.Title = "EditPayPeriodDetail";
    Layout = "~/Views/Shared/_MasterLayout.cshtml";
}

<script src="~/Scripts/HRMS.TIME.Plugins.js"></script>

<html>
<body>

    @using (Html.BeginForm("EditPayPeriodDetail", "PayPeriod", FormMethod.Post))
    {
        @Html.ValidationSummary(true)

        <div class="form-horizontal">
            <div class="form-group">
                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(m => m.PayPeriod.PayPeriodDescription, new { @class = "col-sm-4 control-label required" })
                        <div class="col-sm-8">
                            @Html.TextBoxFor(m => m.PayPeriod.PayPeriodDescription, new { @class = "form-control", placeholder = "Description" })
                            @Html.HiddenFor(m=>m.PayPeriod.PayPeriodId)
                            @Html.HiddenFor(m=>m.PayPeriod.CompanyId)
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.PayPeriod.PayPeriodTypeId, new { @class = "col-sm-4 control-label required" })
                        <div class="col-sm-8">
                            @Html.DropDownListFor(m => m.PayPeriod.PayPeriodTypeId, new SelectList(Model.PayPeriodTypeList, "PayPeriodTypeId", "Name"), "--Select--", new Dictionary<string, Object> { { "class", "form-control" }, { "data-val-1", "Days" }, { "id", "dpPayPeriodType" } })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.PayPeriod.PayPeriodDays, new { @class = "col-sm-4 control-label " })
                        <div class="col-sm-8">
                            @Html.TextBoxFor(m => m.PayPeriod.PayPeriodDays, new { @readonly = "readonly", @class = "form-control", id = "txtpayperioddays", placeholder = "PayPeriod Days" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.PayPeriod.StartDateTime, new { @class = "col-sm-4 control-label  required" })
                        <div class="col-sm-8">
                            <div class="input-group">
                                @Html.TextBoxFor(m => m.PayPeriod.StartDateTime, (Model.PayPeriod.StartDateTime == null ? "" : ((DateTime)Model.PayPeriod.StartDateTime).ToString("MM/dd/yyyy")), new { @onchange = "setPeriodEndValues()", @class = "form-control dateControl", @id = "txtStartDateTime" })
                                <label for="dthiredate" class="input-group-addon btn">
                                    <span class="glyphicon glyphicon-calendar"></span>
                                </label>
                            </div>

                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.PayPeriod.EndDateTime, new { @class = "col-sm-4 control-label " })
                        <div class="col-sm-8">
                            <div class="input-group">
                                @Html.TextBoxFor(m => m.PayPeriod.EndDateTime, (Model.PayPeriod.EndDateTime == null ? "" : ((DateTime)Model.PayPeriod.EndDateTime).ToString("MM/dd/yyyy")), new { @readonly = "readonly", @class = "form-control dateControl", @id = "txtEndDateTime" })
                                <label for="dthiredate" class="input-group-addon btn">
                                    <span class="glyphicon glyphicon-calendar"></span>
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.PayPeriod.StartDayOfWeek, new { @class = "col-sm-4 control-label required" })
                        <div class="col-sm-8">
                            @Html.TextBoxFor(m => m.PayPeriod.StartDayOfWeek, new { @class = "form-control", id = "txtStartDay", placeholder = "Start Day Of Week" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.PayPeriod.NextSchedule, new { @class = "col-sm-4 control-label " })
                        <div class="col-sm-8">
                            @Html.CheckBoxFor(m => m.PayPeriod.NextSchedule, new { @class = "form-control", id = "chkNextSchedule", placeholder = "Builds next schedule on closing the Pay Period" })
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 control-button">
               
                @Html.ActionLink("Cancel", "SelectAllPayPeriodDetails", "PayPeriod", new { @CompanyId = GlobalsVariables.CurrentCompanyId }, new { @class = "btn btn-success" })
                <button type="submit" id="btnsubmit" class="btn btn-success">Save</button>
             </div>
        </div>

    }

    <script type="text/javascript">
        $(document).ready(function () {
            var resultingSiteview = "<h1>PayPeriod <small>Edit PayPeriod </small></h1><ol class=" + '"breadcrumb"' + "><li><a href=" + '"../Home/EmployeeDashboard"' + "><i class=" + '"fa fa-dashboard"' + "></i>Home</a></li><li class=" + '"active"' + ">PayPeriod</li></ol>";
            $("#header-section").empty();
            $("#header-section").html(resultingSiteview);
        });
    </script>

    <script type="text/javascript">
        $(document).ready(function () {
            $("#dpPayPeriodType").change(function () {
                var payperiodTypeIdVal = $(this).val();
                if (payperiodTypeIdVal) {
                    var baseurl = '@System.Configuration.ConfigurationManager.AppSettings["BaseURL"]';
                    baseurl += "PayPeriod/GetPayPeriodDays";
                    $.getJSON(baseurl, { PayPeriodTypeId: payperiodTypeIdVal }, function (payperiodTypeData) {
                        $("#txtpayperioddays").val(payperiodTypeData[0].Days);
                        setPeriodEndValues();
                    });
                }
            });

        });


        function setPeriodEndValues() {
            if (validateNullValue('txtStartDateTime')) {
                var periodDays = $("#txtpayperioddays").val();
                var startDate = new Date($("#txtStartDateTime").val());
                var periodEndDate = new Date(startDate);
                periodEndDate.setDate(periodEndDate.getDate() + parseInt(periodDays - 1));
                $("#txtEndDateTime").val((periodEndDate.getMonth() + 1) + "/" + periodEndDate.getDate() + "/" + periodEndDate.getFullYear());
                var dayOfWeek = new Date($("#txtStartDateTime").val()).getDay();
                switch (dayOfWeek) {
                    case 0:
                        $("#txtStartDay").val("Sunday");
                        break;
                    case 1:
                        $("#txtStartDay").val("Monday");
                        break;
                    case 2:
                        $("#txtStartDay").val("Tuesday");
                        break;
                    case 3:
                        $("#txtStartDay").val("Wednesday");
                        break;
                    case 4:
                        $("#txtStartDay").val("Thursday");
                        break;
                    case 5:
                        $("#txtStartDay").val("Friday");
                        break;
                    case 6:
                        $("#txtStartDay").val("Saturday");
                        break;
                }
            }
        }
    </script>
</body>
</html>

PsplGenericSystem/Extensions/HRMS.Web/Views/PayPeriod/SelectAllPayPeriodDetails.cshtml
@model @HRMS.Web.ViewModels.PayPeriodFormModel
@using HRMS.Common.Helpers;
@using HRMS.Web.Helper;
@{
    ViewBag.Title = "SelectAllPayPeriodDetails";
    Layout = "~/Views/Shared/_MasterLayout.cshtml";
}

<div style="padding-top: 10px;">
    @Html.ActionLink("Add  ", "AddPayPeriodDetail", null, new { @class = "btn btn-success" })
    @Html.ActionLink("Delete", "DeletePayPeriodDetail", null, new { @class = "btn btn-danger", @id = "btnDelete" })
    @Html.ActionLink("<< Back to employee info", "ViewEmployee", "Home", new { @selectedUserId = GlobalsVariables.SelectedUserId }, new { @class = "btn btn-success", style = "float:right" })
</div>
<div id="gridContent" style="padding-top: 10px;">
    <table class="footable table" data-filter="#filter" data-page-size="10" data-page-previous-text="prev" data-page-next-text="next" id="PayPeriodGridContent">
        <thead>
            <tr>
                <th data-sort-ignore="true">
                    <input type="checkbox" />
                </th>
                <th data-toggle="true">
                    @Html.DisplayNameFor(model => model.PayPeriod.PayPeriodDescription)
                </th>
                <th data-hide="phone">
                    @Html.DisplayNameFor(model => model.PayPeriod.PayPeriodTypename)
                </th>
                <th data-hide="phone,tablet">
                    @Html.DisplayNameFor(model => model.PayPeriod.PayPeriodDays)
                </th>
                <th data-hide="phone,tablet">
                    @Html.DisplayNameFor(model => model.PayPeriod.StartDateTime)
                </th>
                <th data-hide="all">
                    @Html.DisplayNameFor(model => model.PayPeriod.EndDateTime)
                </th>
                <th data-hide="all">
                    @Html.DisplayNameFor(model => model.PayPeriod.StartDayOfWeek)
                </th>
                <th data-hide="all">
                    @Html.DisplayNameFor(model => model.PayPeriod.NextSchedule)
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.PayPeriodList)
            {
                <tr>
                    <td>
                        <input type="checkbox" value="" id="@item.PayPeriodId" data-val-1="@item.PayPeriodId" onchange="cbChange(this)" />
                    </td>
                    <td>
                        @Html.ActionLink(((string)item.PayPeriodDescription), "EditPayPeriodDetail", new { @PayPeriodId = item.PayPeriodId }, new { id = "PayPeriodId" })
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PayPeriodTypename)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PayPeriodDays)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.StartDateTime)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EndDateTime)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.StartDayOfWeek)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NextSchedule)
                    </td>
                </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <td colspan="8">
                    <div class="pagination pagination-centered hide-if-no-paging"></div>
                </td>
            </tr>
        </tfoot>
    </table>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        var resultingSiteview = "<h1>PayPeriod <small>PayPeriod List </small></h1><ol class=" + '"breadcrumb"' + "><li><a href=" + '"../Home/EmployeeDashboard"' + "><i class=" + '"fa fa-dashboard"' + "></i>Home</a></li><li class=" + '"active"' + ">PayPeriod</li></ol>";
        $("#header-section").empty();
        $("#header-section").html(resultingSiteview);
    });
</script>

<script type="text/javascript">
    $(document).ready(function () {
        $("#btnDelete").click(function (e) {
            e.preventDefault();
            e.stopPropagation();
            var baseurl = '@System.Configuration.ConfigurationManager.AppSettings["BaseURL"]';
            var searchIDs = $("#PayPeriodGridContent input:checkbox:checked").map(function () {
                return $(this).attr("data-val-1");
            }).get();

            $.ajax({
                url: baseurl + "PayPeriod/DeletePayPeriodDetail",
                type: "POST",
                cache: "false",
                data: { PayPeriodIds: searchIDs.toString() },
                success: function (data) {
                    if (data == "True") {
                        window.location.href = window.location.href;
                    }
                },
                error: function (request, status, error) {
                    alert(request.responseText);
                }
            });
        });
    });
</script>