PsplGenericSystem/Extensions/HRMS.Web/Controllers/InterviewController.cs
using HRMS.Common.Helpers;
using HRMS.Service.Interfaces;
using HRMS.Service.Models.EDM;
using HRMS.Service.Repositories;
using HRMS.Web.Helper;
using HRMS.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using System.Web.Configuration;
using System.Net.Configuration;
using System.Net.Mail;
using System.Configuration;

namespace HRMS.Web.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    public class InterviewController : Controller
    {
        #region //Class Level Variables and Constructor
        private readonly IUtilityRepository _utilityRepository;
        private readonly IFilesDBRepository _filesDbRepository;
        private readonly CompanyRepository _companyRepository;
        private readonly IEmployeeRepository _employeeRepository;
        private readonly IRegisteredUsersRepository _registeredUsersRepository;
        private readonly IInterviewRepository _interviewRepository;
        private readonly IJobApplicantRepository _jobApplicantRepository;
        private readonly IJobProfileRepository _jobProfileRepository;
        public InterviewController(IUtilityRepository utilityRepo, CompanyRepository companyRepository, IFilesDBRepository filesDbRepository,IRegisteredUsersRepository registeredUsersRepository, IEmployeeRepository employeeRepository, IInterviewRepository interviewRepository
            , IJobApplicantRepository jobApplicantRepository, IJobProfileRepository jobProfileRepository)
        {

            _utilityRepository = utilityRepo;
            _filesDbRepository = filesDbRepository;
            _companyRepository = companyRepository;
            _registeredUsersRepository = registeredUsersRepository;
            _employeeRepository = employeeRepository;
            _interviewRepository = interviewRepository;
            _jobApplicantRepository = jobApplicantRepository;
            _jobProfileRepository = jobProfileRepository;
        }
        #endregion
        /// <summary>
        /// View to add an interview schedule to a candidate
        /// </summary>
        /// <returns></returns>
        [Authorize]
        public ActionResult AddInterview()
        {


            var interviewFormModelObj = new InterviewFormModel();
            var lstlookup = _utilityRepository.GetLookUpData(Convert.ToInt32(GlobalsVariables.CurrentCompanyId));
            interviewFormModelObj.Interview = new Interview();
            if (!string.IsNullOrEmpty(Request.QueryString["InterviewId"]))
            {
                interviewFormModelObj.Interview.InterviewId = Convert.ToInt32(Request.QueryString["InterviewId"]);
                interviewFormModelObj.Interview = _interviewRepository.InterviewSelect(interviewFormModelObj.Interview.InterviewId);

            }
            var lookUpDataEntityobj = new LookUpDataEntity { Name = LocalizedStrings.AddNew, Id = 0 };
            interviewFormModelObj.InterviewType = lstlookup.Where(j => j.TableName == LocalizedStrings.InterviewType).ToList();
            interviewFormModelObj.InterviewType.Insert(0, lookUpDataEntityobj);
            interviewFormModelObj.InterviewRoom = lstlookup.Where(j => j.TableName == LocalizedStrings.InterviewRoom).ToList();
            interviewFormModelObj.InterviewRoom.Insert(0, lookUpDataEntityobj);
            interviewFormModelObj.InterviewStatus = lstlookup.Where(j => j.TableName == LocalizedStrings.InterviewStatus).ToList();
            interviewFormModelObj.InterviewStatus.Insert(0, lookUpDataEntityobj);

            interviewFormModelObj.EmployeeList = _registeredUsersRepository.SelectAllEmployeesList(Convert.ToInt32(GlobalsVariables.CurrentCompanyId));
            if (!string.IsNullOrEmpty(Request.QueryString["applicantId"]) && !string.IsNullOrEmpty(Request.QueryString["jobProfileId"]))
            {
                interviewFormModelObj.Interview = new Interview();
                interviewFormModelObj.Interview.CandidateId = Convert.ToInt32(Request.QueryString["applicantId"]);
                interviewFormModelObj.Interview.JobProfileId = Convert.ToInt32(Request.QueryString["jobProfileId"]);
                var applicantinfo = _jobApplicantRepository.SelectJobApplicantById(Convert.ToInt32(interviewFormModelObj.Interview.CandidateId), Convert.ToInt32(GlobalsVariables.CurrentCompanyId));
                interviewFormModelObj.Interview.ApplicantName = applicantinfo.FirstName + " " + applicantinfo.LastName;
                var jobinfo = _jobProfileRepository.SelectJobProfileById(interviewFormModelObj.Interview.JobProfileId);
                interviewFormModelObj.Interview.JobTitle = jobinfo.Title;
            }


            var jobInterviewers = _interviewRepository.JobInterviewers(interviewFormModelObj.Interview.InterviewId);

            var result = (from employees in interviewFormModelObj.EmployeeList
                          join jobinterviewer in jobInterviewers on employees.UserId equals jobinterviewer.InterviewerId into gj
                          from sublist in gj.DefaultIfEmpty()
                          select new { employees.UserId, employees.UserName, InterviewerStatus = (sublist == null ? false : true) }).ToList();

            interviewFormModelObj.InterviewersList = result.Select(userObj => new Interviewers
            {
                InterviewerId = userObj.UserId,
                InterviewerName = userObj.UserName,
                InterviewerStatus = userObj.InterviewerStatus
            }).ToList();


            return View(interviewFormModelObj);
        }
        /// <summary>
        /// Method to Post InterviewDetails to Database
        /// </summary>
        /// <param name="interviewFormModelObj"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult AddInterview(InterviewFormModel interviewFormModelObj)
        {
            int companyId = Convert.ToInt32(GlobalsVariables.CurrentCompanyId);
            var lstlookup = _utilityRepository.GetLookUpData(Convert.ToInt32(GlobalsVariables.CurrentCompanyId));
            interviewFormModelObj.Interview.CompanyId = Convert.ToInt32(GlobalsVariables.CurrentCompanyId);
            interviewFormModelObj.Interview.CreatedBy = Convert.ToInt32(GlobalsVariables.SelectedUserId);
            interviewFormModelObj.Interview.ModifiedBy = Convert.ToInt32(GlobalsVariables.SelectedUserId);
            var jobProfileObj = _jobProfileRepository.SelectJobProfileById(interviewFormModelObj.Interview.JobProfileId);
            var applicantObj = _jobApplicantRepository.SelectJobApplicantById(Convert.ToInt32(interviewFormModelObj.Interview.CandidateId), companyId);
            int result;
            
            //var resumeInfoFromFile = _filesDbRepository.SelectFileByFileDBId(applicantObj.ResumeAttachmentId);
            var jobInterviewersList = new List<JobInterviewers>();
            if (interviewFormModelObj.InterviewersList != null)
            {
                foreach (var interviewerId in interviewFormModelObj.InterviewersIdList.Split(','))
                {
                    var jobInterviewersObj = new JobInterviewers();
                    jobInterviewersObj.InterviewerId = Convert.ToInt32(interviewerId);
                    jobInterviewersList.Add(jobInterviewersObj);
                }
            }
            if (interviewFormModelObj.Interview.InterviewId.Equals(0))
            {
                result = _interviewRepository.CreateInterview(interviewFormModelObj.Interview, jobInterviewersList);
                interviewFormModelObj.Interview.InterviewId = result;
                if (!interviewFormModelObj.Interview.JobProfileId.Equals(0) && !interviewFormModelObj.Interview.CandidateId.Equals(0))
                {
                    ApplicantInterview applicantInterviewObj = new ApplicantInterview();
                    applicantInterviewObj.InterviewId = interviewFormModelObj.Interview.InterviewId;
                    applicantInterviewObj.JobApplicantId = Convert.ToInt32(interviewFormModelObj.Interview.CandidateId);
                    applicantInterviewObj.JobProfileId = interviewFormModelObj.Interview.JobProfileId;
                    var applicantinterviewstatus = _interviewRepository.ApplicantInterviews(applicantInterviewObj);
                }
            }
            else
            {
                result = _interviewRepository.UpdateInterview(interviewFormModelObj.Interview);
            }
            var emailto = _interviewRepository.InterviewSelect(interviewFormModelObj.Interview.InterviewId);
            interviewFormModelObj.Interview.SendCandidateEmail1 = emailto.SendCandidateEmail1;
            interviewFormModelObj.Interview.SendInterviewerEmail1 = emailto.SendInterviewerEmail1;
            var interviewerList = _interviewRepository.JobInterviewers(interviewFormModelObj.Interview.InterviewId);
            if (applicantObj != null && jobProfileObj != null)
            {
                string jobProfileTitle = jobProfileObj.Title;
                string applicantName = applicantObj.FirstName + " " + applicantObj.LastName;
                string applicantEmailId = applicantObj.Email;
                if (interviewerList.Count > 0)
                {
                    foreach (var interviewer in interviewerList)
                    {
                        var employeeObj = _employeeRepository.SelectEmployeeById(interviewer.InterviewerId, companyId);
                        List<Interview> interviewInfoList = _interviewRepository.InterviewSelectAll(Convert.ToInt32(GlobalsVariables.CurrentCompanyId));
                        //Send an email notification for interview schedule to interviewers
                        if (interviewFormModelObj.Interview.SendInterviewerEmail1)
                        {
                            var interviewInfo = interviewInfoList.Where(j => j.InterviewId == interviewFormModelObj.Interview.InterviewId).FirstOrDefault();                                                     

PsplGenericSystem/Extensions/HRMS.Web/Views/Interview/AddInterview.cshtml
@model HRMS.Web.ViewModels.InterviewFormModel
@using HRMS.Web.Helper
@using HRMS.Common.Helpers
@{
    ViewBag.Title = "AddInterview";
    Layout = "~/Views/Shared/_MasterLayout.cshtml";
}
<html>
<head>
    <title>Scheduling Interview</title>
</head>
<body>
    @using (Html.BeginForm("AddInterview", "Interview", FormMethod.Post))
    {
        <div class="form-horizontal">
            <div class="form-group">
                <div class="col-md-10">
                    <fieldset>
                        <div>
                            @Html.HiddenFor(j => j.Interview.CandidateId)
                            @Html.HiddenFor(j => j.Interview.JobProfileId)
                        </div>
                        <div class="form-group">
                            @Html.Label("Applicant Name", new { @class = "col-sm-4 control-label" })
                            <div class="col-sm-6">
                                @Html.TextBoxFor(m => m.Interview.ApplicantName, new { @class = "form-control", @disabled = "disabled" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.Label("JobTitle", new { @class = "col-sm-4 control-label" })
                            <div class="col-sm-6">
                                @Html.TextBoxFor(m => m.Interview.JobTitle, new { @class = "form-control", @disabled = "disabled" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(j => j.Interview.Type, new { @class = "col-sm-4 control-label" })
                            <div class="col-sm-6">
                                @Html.DropDownListFor(j => j.Interview.Type, new SelectList(Model.InterviewType, "ID", "Name"), "--select--", new { @class = " drplookup form-control", @data_val_1 = LocalizedStrings.InterviewType })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(j => j.Interview.InterviewDate, new { @class = "col-sm-4 control-label required" })
                            <div class="col-sm-6">
                                <div class="input-group">
                                    @Html.TextBoxFor(m => m.Interview.InterviewDate, (Model.Interview.InterviewDate == null ? "" : ((DateTime)Model.Interview.InterviewDate).ToString("MM/dd/yyyy")), new { @class = "form-control dateControl", @maxlength = "10", @id = "dtinterviewdate" })
                                    <label for="dtinterviewdate" class="input-group-addon btn">
                                        <span class="glyphicon glyphicon-calendar"></span>
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(j => j.Interview.InterviewRoom, new { @class = "col-sm-4 control-label" })
                            <div class="col-sm-6">
                                @Html.DropDownListFor(j => j.Interview.InterviewRoom, new SelectList(Model.InterviewRoom, "ID", "Name"), "--select--", new { @class = " drplookup form-control", @data_val_1 = LocalizedStrings.InterviewRoom })
                            </div>
                        </div>
                        <div class="bootstrap-timepicker">
                            <div class="form-group">
                                @Html.LabelFor(j => j.Interview.ScheduledInterviewTime, new { @class = "col-sm-4 control-label required" })
                                <div class="col-sm-6">
                                    <div class="input-group">
                                        @Html.TextBoxFor(m => m.Interview.ScheduledInterviewTime, (Model.Interview.ScheduledInterviewTime == null ? "" : (Model.Interview.ScheduledInterviewTime).ToString()), new { @class = "form-control timepicker", @maxlength = "10", @id = "dtinterviewtime" })
                                        @*<input type="text" class="form-control timepicker" />*@
                                        <div class="input-group-addon">
                                            <i class="fa fa-clock-o"></i>
                                        </div>
                                    </div>

                                </div><!-- /.input group -->
                            </div><!-- /.form group -->
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(j => j.Interview.CandidateInstructions, new { @class = "col-sm-4 control-label" })
                            <div class="col-sm-6">
                                @Html.TextAreaFor(j => j.Interview.CandidateInstructions, new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(j => j.Interview.InterviewerInstructions, new { @class = "col-sm-4 control-label" })
                            <div class="col-sm-6">
                                @Html.TextAreaFor(j => j.Interview.InterviewerInstructions, new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(j => j.Interview.Status, new { @class = "col-sm-4 control-label" })
                            <div class="col-sm-6">
                                @Html.DropDownListFor(j => j.Interview.Status, new SelectList(Model.InterviewStatus, "ID", "Name"), "--select--", new { @class = " drplookup form-control", @data_val_1 = LocalizedStrings.InterviewStatus })
                            </div>
                        </div>

                    </fieldset>
                    <fieldset>
                        <div class="form-group">
                            <div class="col-sm-4">
                                <label>Interviewers</label>
                                <div id="selectinterviewers" style="max-height:200px; overflow-y:scroll;">
                                    <ul style="list-style: none; padding: 0;border:1px" id="interviewerslist">

                                        @foreach (var a in Model.InterviewersList)
                                        {
                                            <li>@Html.CheckBox("Interviewers", a.InterviewerStatus, new { @id = a.InterviewerId }) @a.InterviewerName </li>
                                        }
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.CheckBoxFor(j => j.Interview.SendInterviewerEmail1, new { @class = "col-sm-2 control-label" })
                            @Html.LabelFor(j => j.Interview.SendInterviewerEmail, new { @class = "control-label" })
                        </div>
                        <div class="form-group">
                            @Html.CheckBoxFor(j => j.Interview.SendCandidateEmail1, new { @class = "col-sm-2 control-label" })
                            @Html.LabelFor(j => j.Interview.SendCandidateEmail, new { @class = "control-label" })
                        </div>
                        @Html.HiddenFor(j => j.Interview.InterviewId)  
                        @Html.HiddenFor(j => j.InterviewersIdList, new { @id = "hdninterviewerIds" })
                    </fieldset>
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-6 control-button">
                
                @Html.ActionLink("Cancel", "InterviewSelectAll", "Interview","", new { @class = "btn btn-success" })
                <button type="submit" id="btnsubmit" class="btn btn-success">Save</button>
            </div>
        </div>
    }
</body>
</html>
<script type="text/javascript">
    $(document).ready(function () {
        var resultingSiteview = "<h1>Scheduling Interview</h1><ol class=" + '"breadcrumb"' + "><li><a href=" + '"../Home/EmployeeDashboard"' + "><i class=" + '"fa fa-dashboard"' + "></i>Home</a></li><li><a href=" + '"../Home/SelectOnBoardingStep"' + ">Select On Boarding step</a></li><li><a href=" + '"../Interview/AddInterview"' + ">Interview</a></li>";
        $("#header-section").empty();
        $("#header-section").html(resultingSiteview);
        $("#btnCreateandPost").click(function () {
            $('#isPosted').attr('value', 'true');
        });
        $('#btnAddInterview').click(function (e) {
            e.preventDefault();
            e.stopImmediatePropagation();
            var baseurl = '@System.Configuration.ConfigurationManager.AppSettings["BaseURL"]';
            //if ($("#addnewemployeeview").valid()) { //if you use validation
            //    $.ajax({
            //        url: baseurl + "Home/AddInterview",
            //        type: 'POST',
            //        data: $("#addnewemployeeview").serialize(),
            //        success: function (data) {
            //            window.location.href = baseurl + "Home/ConfigureEmployee";
            //        }
            //    });
            //    }
        });
    });


    $("#btnsubmit").click(function () {

        var InterviewersCount = $('#interviewerslist :checked').map(function () {
            return this.id;
        }).get();
        $('#hdninterviewerIds').attr('value', InterviewersCount);
    });
</script>
<script type="text/javascript">
    $(document).ready(function () {
        var selectedDate = $('#dtinterviewdate').datepicker('getDate');
        var now = new Date();
        if (selectedDate < now) {
            // selected date is in the past
        }
    });
</script>

PsplGenericSystem/Extensions/HRMS.Web/Views/Interview/InterviewSelectAll.cshtml
@model IEnumerable<HRMS.Service.Models.EDM.Interview>
@using HRMS.Web.Helper;
@{
    ViewBag.Title = "InterviewSelectAll";
    Layout = "~/Views/Shared/_MasterLayout.cshtml";
}

<div>
    @Html.ActionLink("Add", "AddInterview", null, new { @class = "btn btn-success" })
    @Html.ActionLink("Delete", "DeleteInterview", null, new { @class = "btn btn-danger", @id = "btnDeleteinterview" })
    @Html.ActionLink("<< Back to Candidate Preview", "CandidatePreview", "Recruiting", new { @JobApplicantId = GlobalsVariables.SelectedCandidateId }, new { @class = "btn btn-success", style = "float:right" })
</div>
<div id="gridContent" style="padding-top: 10px;">
    <table class="footable table" data-filter="#filter" data-page-size="10" data-page-previous-text="prev" data-page-next-text="next" id="InterviewGridContent">
        <thead>
            <tr>
                <th data-sort-ignore="true">
                    <input type="checkbox" />
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ApplicantName)
                </th>
                <th data-hide="phone">
                    @Html.DisplayNameFor(model => model.JobTitle)
                </th>
                <th data-hide="phone,tablet">
                    @Html.DisplayNameFor(model => model.Type)
                </th>
                <th data-hide="phone,tablet">
                    @Html.DisplayNameFor(model => model.InterviewRoom)
                </th>
                <th data-hide="phone,tablet">
                    @Html.DisplayNameFor(model => model.Status)
                </th>

            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        <input type="checkbox" value="" data-val-1="@item.InterviewId" class="btncheckinterview" onchange="cbChange(this)" />
                    </td>
                    <td>
                        @{
                            if (item.ApplicantName != null)
                            {                               
                            @Html.ActionLink(item.ApplicantName, "AddInterview", new { @InterviewId = item.InterviewId }, new { id = "InterviewID" })
                            }
                        }
                    </td>
                    <td>
                        @{
                             if (item.JobTitle != null)
                            {
                                @Html.Label(item.JobTitle)
                            }
                        }
                    </td>
                    <td>
                        @Html.Label(Convert.ToString(item.InterviewType))
                    </td>
                    <td>
                        @Html.Label(Convert.ToString(item.Room))
                    </td>
                    <td>
                        @Html.Label(Convert.ToString(item.InterviewStatus))
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        var resultingSiteview = "<h1>Interviews</h1><ol class=" + '"breadcrumb"' + "><li><a href=" + '"../Home/EmployeeDashboard"' + "><i class=" + '"fa fa-dashboard"' + "></i>Home</a></li><li class=" + '"active"' + ">Interview</li></ol>";
        $("#header-section").empty();
        $("#header-section").html(resultingSiteview);
        $("#btnDeleteinterview").click(function (e) {
            e.preventDefault();
            e.stopPropagation();
            var baseurl = '@System.Configuration.ConfigurationManager.AppSettings["BaseURL"]';
            var searchIDs = $("#InterviewGridContent input:checkbox:checked").map(function () {
                return $(this).attr("data-val-1");
            }).get();
            if (searchIDs.toString().length > 0) {
                $.ajax({
                    url: baseurl + "Interview/DeleteInterview",
                    type: "POST",
                    cache: "false",
                    data: { deleteInterviewIds: searchIDs.toString() },
                    success: function (data) {
                        if (data == "True") {
                            window.location.href = window.location.href;
                        }
                    },
                    error: function (request, status, error) {
                    }
                });
            }
            else { alert("Please select item(s) to delete."); }
        });
    });
</script>