PsplGenericSystem/Extensions/HRMS.Web/Controllers/RoundingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HRMS.Service.Models.EDM;
using HRMS.Web.Helper;
using HRMS.Web.Areas.HireWizard.Models;
using HRMS.Service.Interfaces;
using HRMS.Web.ViewModels;

namespace HRMS.Web.Controllers
{
    public class RoundingController : Controller
    {
        #region Class Level Variables and constructor

        private readonly IRoundingRepository _roundingRepository;
        private readonly IRoundTypeRepository _roundTypeRepository;
        private readonly IRoundMinuteRepository _roundMinuteRepository;

        public RoundingController(IRoundingRepository roundingRepository, IRoundTypeRepository roundTypeRepository, IRoundMinuteRepository roundMinuteRepository)
        {
            _roundingRepository = roundingRepository;
            _roundTypeRepository = roundTypeRepository;
            _roundMinuteRepository = roundMinuteRepository;
        }

        protected IRoundingRepository RoundingRepository
        {
            get { return _roundingRepository; }
        }
        protected IRoundTypeRepository RoundTypeRepository
        {
            get { return _roundTypeRepository; }
        }
        protected IRoundMinuteRepository RoundMinuteRepository
        {
            get { return _roundMinuteRepository; }
        }

        #endregion


        /// <summary>
        /// Returns Rounding List by CompanyId
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [ActionName("SelectAllRoundingDetails")]
        public ActionResult SelectAllRoundingDetails()
        {
            RoundingFormModel roundingFormModelObj = new RoundingFormModel();
            List<Rounding> roundingInfoList = _roundingRepository.SelectAllRoundingDetailsByCompanyId(Convert.ToInt32(GlobalsVariables.CurrentCompanyId));
            var RoundTypeList = _roundTypeRepository.SelectAllRoundTypeDetails(Convert.ToInt32(GlobalsVariables.CurrentCompanyId));

            for (int i = 0; i < roundingInfoList.Count; i++)
            {
                roundingInfoList[i].WorkStartTypeName = RoundTypeList.Where(rt => rt.RoundTypeId == roundingInfoList[i].StartRoundType).Select(rt => rt.Name).SingleOrDefault();
                roundingInfoList[i].WorkEndTypeName = RoundTypeList.Where(rt => rt.RoundTypeId == roundingInfoList[i].EndRoundType).Select(rt => rt.Name).SingleOrDefault();
                roundingInfoList[i].LunchStartTypeName = RoundTypeList.Where(rt => rt.RoundTypeId == roundingInfoList[i].LunchStartRoundType).Select(rt => rt.Name).SingleOrDefault();
                roundingInfoList[i].LunchEndTypeName = RoundTypeList.Where(rt => rt.RoundTypeId == roundingInfoList[i].LunchEndRoundType).Select(rt => rt.Name).SingleOrDefault();
                roundingInfoList[i].BreakStartTypeName = RoundTypeList.Where(rt => rt.RoundTypeId == roundingInfoList[i].BreakStartRoundType).Select(rt => rt.Name).SingleOrDefault();
                roundingInfoList[i].BreakEndTypeName = RoundTypeList.Where(rt => rt.RoundTypeId == roundingInfoList[i].BreakEndRoundType).Select(rt => rt.Name).SingleOrDefault();
            }

            roundingFormModelObj.RoundingList = roundingInfoList;

            return View(roundingFormModelObj);
        }


        /// <summary>
        /// AddRoundngDetail - Get Method: Returns the RoundingInsert View.
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [ActionName("AddRoundingDetail")]
        public ActionResult AddRoundingDetail()
        {
            RoundingFormModel roundingFormModelObj = new RoundingFormModel();

            roundingFormModelObj.RoundTypeList = _roundTypeRepository.SelectAllRoundTypeDetails(Convert.ToInt32(GlobalsVariables.CurrentCompanyId));
            roundingFormModelObj.RoundMinuteList = _roundMinuteRepository.SelectAllRoundMinuteDetails(Convert.ToInt32(GlobalsVariables.CurrentCompanyId));

            return View(roundingFormModelObj);
        }


        /// <summary>
        /// AddRoundngDetail - Post Method: Inserts New Rounding Details.
        /// </summary>
        /// <param name="lunchItem"></param>
        /// <returns></returns>
        [HttpPost]
        [ActionName("AddRoundingDetail")]
        public ActionResult AddRoundingDetail(RoundingFormModel roundingItem)
        {

            bool success = false;
            if (ModelState.IsValid)
            {
                roundingItem.Rounding.CompanyId = Convert.ToInt32(GlobalsVariables.CurrentCompanyId);
                success = _roundingRepository.InsertRounding(roundingItem.Rounding);
            }

            if (success)
                return RedirectToAction("SelectAllRoundingDetails");
            return View();
        }


        /// <summary>
        /// EditRounding - Get Method: Returns the EditRounding View.
        /// </summary>
        /// <param name="LunchId"></param>
        /// <returns></returns>
        [HttpGet]
        [ActionName("EditRoundingDetail")]
        public ActionResult EditRoundingDetail(int RoundingId)
        {
            //  int decrytedRoundingId = Convert.ToInt32(Encryption.Decrypt(RoundingId));

            RoundingFormModel RoundingFormModelObj = new RoundingFormModel();


           Rounding RoundingDetailObj = _roundingRepository.SelectRoundingDetailsByRoundingId(RoundingId, Convert.ToInt32(GlobalsVariables.CurrentCompanyId));
           List<RoundType> roundTypeList = _roundTypeRepository.SelectAllRoundTypeDetails(Convert.ToInt32(GlobalsVariables.CurrentCompanyId));
           List<RoundMinute> RoundMinutesList = _roundMinuteRepository.SelectAllRoundMinuteDetails(Convert.ToInt32(GlobalsVariables.CurrentCompanyId));

           RoundingFormModelObj.Rounding = RoundingDetailObj;
           RoundingFormModelObj.RoundTypeList = roundTypeList;
           RoundingFormModelObj.RoundMinuteList = RoundMinutesList;

           return View(RoundingFormModelObj);
        }


        /// <summary>
        /// EditRounding - Post Method: Updates the Rounding Information.
        /// </summary>
        /// <param name="lunchItem"></param>
        /// <returns></returns>
        [HttpPost]
        [ActionName("EditRoundingDetail")]
        public ActionResult EditRoundingDetail(RoundingFormModel roundingItem)
        {
            bool success = false;

            if (ModelState.IsValid)
            {
                success = _roundingRepository.UpdateRounding(roundingItem.Rounding);
            }

            if (success)
                return RedirectToAction("SelectAllRoundingDetails");
            return View();
        }



        /// <summary>
        /// DeleteRounding - Get Method: Deletes the Rounding Information
        /// </summary>
        /// <param name="RoundingId"></param>
        /// <returns></returns>
        [HttpPost]
        [ActionName("DeleteRoundingDetail")]
        public bool DeleteRoundingDetail(string RoundingIds)
        {

            if (RoundingIds != null)
            {
                foreach (var RoundingId in RoundingIds.Split(','))
                {
                    var deleteRoundingDetail =
                         _roundingRepository.DeleteroundingDetail(Int32.Parse(RoundingId), Convert.ToInt32(GlobalsVariables.CurrentCompanyId));
                }
            }
            return true;
        }
	}
}

PsplGenericSystem/Extensions/HRMS.Web/Views/Rounding/AddRoundingDetail.cshtml
@model @HRMS.Web.ViewModels.RoundingFormModel
@using HRMS.Web.Helper;
@using System.Web.Optimization;
@{
    ViewBag.Title = "AddRoundingDetail";
    Layout = "~/Views/Shared/_MasterLayout.cshtml";
}

<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Add Rounding Detail</title>

</head>
<body>

    @using (Html.BeginForm("AddRoundingDetail", "Rounding", FormMethod.Post))
    {

        <div class="form-horizontal">
            <fieldset>
                <div class="col-sm-6">
                    <div class="form-group">
                        @Html.LabelFor(m => m.Rounding.RoundingDescription, new { @class = "col-sm-4 control-label required" })
                        <div class="col-sm-8">
                            @Html.TextBoxFor(m => m.Rounding.RoundingDescription, new { @class = "form-control", placeholder = "Rounding Description" })
                        </div>
                    </div>
                </div>
            </fieldset>

            <fieldset>
                <legend>Work Time</legend>
                <div class="col-sm-6">
                    <div class="form-group">
                        @Html.LabelFor(m => m.Rounding.StartRoundType, new { @class = "col-sm-4 control-label required" })
                        <div class="col-sm-8">
                            @Html.DropDownListFor(m => m.Rounding.StartRoundType, new SelectList(Model.RoundTypeList, "RoundTypeId", "Name"), "--Select--", new Dictionary<string, Object> { { "class", "form-control" }, { "data-val-1", "Days" }, { "id", "dpSRoundType" } })
                        </div>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        @Html.LabelFor(m => m.Rounding.StartRoundMinutes, new { @class = "col-sm-4 control-label required " })
                        <div class="col-sm-8">
                            @Html.DropDownListFor(m => m.Rounding.StartRoundMinutes, new SelectList(Model.RoundMinuteList, "RoundMinutesId", "Name"), "--Select--", new Dictionary<string, Object> { { "class", "form-control" }, { "data-val-1", "Days" }, { "id", "dpSRoundMinutes" } })
                        </div>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        @Html.LabelFor(m => m.Rounding.EndRoundType, new { @class = "col-sm-4 control-label required" })
                        <div class="col-sm-8">
                            @Html.DropDownListFor(m => m.Rounding.EndRoundType, new SelectList(Model.RoundTypeList, "RoundTypeId", "Name"), "--Select--", new Dictionary<string, Object> { { "class", "form-control" }, { "data-val-1", "Days" }, { "id", "dpERoundType" } })
                        </div>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        @Html.LabelFor(m => m.Rounding.EndPunchMinutes, new { @class = "col-sm-4 control-label required" })
                        <div class="col-sm-8">
                            @Html.DropDownListFor(m => m.Rounding.EndPunchMinutes, new SelectList(Model.RoundMinuteList, "RoundMinutesId", "Name"), "--Select--", new Dictionary<string, Object> { { "class", "form-control" }, { "data-val-1", "Days" }, { "id", "dpEPunchMinutes" } })
                        </div>
                    </div>
                </div>
            </fieldset>


            <fieldset>
                <legend>Lunch Time</legend>
                <div class="col-sm-6">
                    <div class="form-group">
                        @Html.LabelFor(m => m.Rounding.LunchStartRoundType, new { @class = "col-sm-4 control-label" })
                        <div class="col-sm-8">
                            @Html.DropDownListFor(m => m.Rounding.LunchStartRoundType, new SelectList(Model.RoundTypeList, "RoundTypeId", "Name"), "--Select--", new Dictionary<string, Object> { { "class", "form-control" }, { "data-val-1", "Days" }, { "id", "dpLSRoundType" } })
                        </div>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        @Html.LabelFor(m => m.Rounding.LunchStartRoundMinutes, new { @class = "col-sm-4 control-label" })
                        <div class="col-sm-8">
                            @Html.DropDownListFor(m => m.Rounding.LunchStartRoundMinutes, new SelectList(Model.RoundMinuteList, "RoundMinutesId", "Name"), "--Select--", new Dictionary<string, Object> { { "class", "form-control" }, { "data-val-1", "Days" }, { "id", "dpLSRoundMinutes" } })
                        </div>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        @Html.LabelFor(m => m.Rounding.LunchEndRoundType, new { @class = "col-sm-4 control-label " })
                        <div class="col-sm-8">
                            @Html.DropDownListFor(m => m.Rounding.LunchEndRoundType, new SelectList(Model.RoundTypeList, "RoundTypeId", "Name"), "--Select--", new Dictionary<string, Object> { { "class", "form-control" }, { "data-val-1", "Days" }, { "id", "dpLERoundType" } })
                        </div>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        @Html.LabelFor(m => m.Rounding.LunchEndRoundTMinutes, new { @class = "col-sm-4 control-label" })
                        <div class="col-sm-8">
                            @Html.DropDownListFor(m => m.Rounding.LunchEndRoundTMinutes, new SelectList(Model.RoundMinuteList, "RoundMinutesId", "Name"), "--Select--", new Dictionary<string, Object> { { "class", "form-control" }, { "data-val-1", "Days" }, { "id", "dpLERoundMinutes" } })
                        </div>
                    </div>
                </div>
            </fieldset>


            <fieldset>
                <legend>Break Time</legend>
                <div class="col-sm-6">
                    <div class="form-group">
                        @Html.LabelFor(m => m.Rounding.BreakStartRoundType, new { @class = "col-sm-4 control-label" })
                        <div class="col-sm-8">
                            @Html.DropDownListFor(m => m.Rounding.BreakStartRoundType, new SelectList(Model.RoundTypeList, "RoundTypeId", "Name"), "--Select--", new Dictionary<string, Object> { { "class", "form-control" }, { "data-val-1", "Days" }, { "id", "dpBSRoundType" } })
                        </div>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        @Html.LabelFor(m => m.Rounding.BreakStartRoundMinutes, new { @class = "col-sm-4 control-label" })
                        <div class="col-sm-8">
                            @Html.DropDownListFor(m => m.Rounding.BreakStartRoundMinutes, new SelectList(Model.RoundMinuteList, "RoundMinutesId", "Name"), "--Select--", new Dictionary<string, Object> { { "class", "form-control" }, { "data-val-1", "Days" }, { "id", "dpBSRoundMinutes" } })
                        </div>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        @Html.LabelFor(m => m.Rounding.BreakEndRoundType, new { @class = "col-sm-4 control-label" })
                        <div class="col-sm-8">
                            @Html.DropDownListFor(m => m.Rounding.BreakEndRoundType, new SelectList(Model.RoundTypeList, "RoundTypeId", "Name"), "--Select--", new Dictionary<string, Object> { { "class", "form-control" }, { "data-val-1", "Days" }, { "id", "dpBERoundType" } })
                        </div>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        @Html.LabelFor(m => m.Rounding.BreakEndRoundTMinutes, new { @class = "col-sm-4 control-label" })
                        <div class="col-sm-8">
                            @Html.DropDownListFor(m => m.Rounding.BreakEndRoundTMinutes, new SelectList(Model.RoundMinuteList, "RoundMinutesId", "Name"), "--Select--", new Dictionary<string, Object> { { "class", "form-control" }, { "data-val-1", "Days" }, { "id", "dpBERoundMinutes" } })
                        </div>
                    </div>
                </div>
            </fieldset>


            <fieldset>
                <legend>Report Exception Configuration</legend>
                <div class="col-sm-6">
                    <div class="form-group">
                        @Html.LabelFor(m => m.Rounding.ReportEarlyIn, new { @class = "col-sm-4 control-label" })
                        <div class="col-sm-8">
                            @Html.TextBoxFor(m => m.Rounding.ReportEarlyIn, new { @class = "form-control", placeholder = "Early In" })
                        </div>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        @Html.LabelFor(m => m.Rounding.ReportEarlyOut, new { @class = "col-sm-4 control-label" })
                        <div class="col-sm-8">
                            @Html.TextBoxFor(m => m.Rounding.ReportEarlyOut, new { @class = "form-control", placeholder = "Early Out" })
                        </div>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        @Html.LabelFor(m => m.Rounding.ReportLateIn, new { @class = "col-sm-4 control-label" })
                        <div class="col-sm-8">
                            @Html.TextBoxFor(m => m.Rounding.ReportLateIn, new { @class = "form-control", placeholder = "Late In" })
                        </div>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        @Html.LabelFor(m => m.Rounding.ReportLateOut, new { @class = "col-sm-4 control-label" })
                        <div class="col-sm-8">
                            @Html.TextBoxFor(m => m.Rounding.ReportLateOut, new { @class = "form-control", placeholder = "Late Out" })
                        </div>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        @Html.LabelFor(m => m.Rounding.ReportLunchUnder, new { @class = "col-sm-4 control-label" })
                        <div class="col-sm-8">
                            @Html.TextBoxFor(m => m.Rounding.ReportLunchUnder, new { @class = "form-control", placeholder = "Lunch Under" })
                        </div>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        @Html.LabelFor(m => m.Rounding.ReportLunchOver, new { @class = "col-sm-4 control-label" })
                        <div class="col-sm-8">
                            @Html.TextBoxFor(m => m.Rounding.ReportLunchOver, new { @class = "form-control", placeholder = "lunch Over" })
                        </div>
                    </div>
                </div>
            </fieldset>

        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 control-button">
                <button type="submit" id="btnsubmit" class="btn btn-success">Save</button>
                @Html.ActionLink("Cancel", "SelectAllRoundingDetails", "Rounding", new { @CompanyId = GlobalsVariables.CurrentCompanyId }, new { @class = "btn btn-success" })
            </div>
        </div>

    }

    <script type="text/javascript">
        $(document).ready(function () {
            var resultingSiteview = "<h1>Rounding <small>Add Rounding </small></h1><ol class=" + '"breadcrumb"' + "><li><a href=" + '"../Home/EmployeeDashboard"' + "><i class=" + '"fa fa-dashboard"' + "></i>Home</a></li><li class=" + '"active"' + ">Rounding</li></ol>";
            $("#header-section").empty();
            $("#header-section").html(resultingSiteview);
        });
    </script>
</body>
</html>

PsplGenericSystem/Extensions/HRMS.Web/Views/Rounding/SelectAllRoundingDetails.cshtml
@model HRMS.Web.ViewModels.RoundingFormModel
@{
    ViewBag.Title = "SelectAllRoundingDetails";
    Layout = "~/Views/Shared/_MasterLayout.cshtml";
}
<div style="padding-top: 10px;">
    @Html.ActionLink("Add  ", "AddRoundingDetail", null, new { @class = "btn btn-success" })
    @Html.ActionLink("Delete", "DeleteRoundingDetail", null, new { @class = "btn btn-danger", @id = "btnDelete" })
    @Html.ActionLink("<< Back to TimeAttendance Configuration", "TimeAttendanceConfiguration", "Home", null, new { @class = "btn btn-success", style = "float:right" })
</div>
<div id="gridContent" style="padding-top: 10px;">
    <table class="footable table" data-filter="#filter" data-page-size="5" data-page-previous-text="prev" data-page-next-text="next" id="RoundingGridContent">
        <thead>
            <tr>
                <th data-sort-ignore="true">
                    <input type="checkbox" />
                </th>
                <th data-toggle="true">
                    @Html.DisplayNameFor(Model => Model.Rounding.RoundingDescription)
                </th>
                <th>
                    @Html.DisplayName("Work Start Type")
                </th>
                <th data-hide="phone">
                    @Html.DisplayName("Work End  Type")
                </th>
                <th data-hide="phone,tablet">
                    @Html.DisplayName("Lunch Start Type")
                </th>
                <th data-hide="phone,tablet">
                    @Html.DisplayName("Lunch End Type")
                </th>
                <th data-hide="all">
                    @Html.DisplayName("Break Start Type")
                </th>
                <th data-hide="all">
                    @Html.DisplayName("Break End Type")
                </th>
            </tr>
        </thead>
        <tbody>
           @for (int i = 0; i< Model.RoundingList.Count  ;i++)
{
                <tr>
                    <td>
                        <input type="checkbox" value="" id="@Model.RoundingList[i].RoundingId" data-val-1="@Model.RoundingList[i].RoundingId" onchange="cbChange(this)" />
                    </td>

                    <td>
                        @Html.ActionLink(((string)Model.RoundingList[i].RoundingDescription), "EditRoundingDetail", new { @RoundingId = Model.RoundingList[i].RoundingId }, new { id = "RoundingId" })
                    </td>
                    <td>
                        @Html.DisplayFor(m => m.RoundingList[i].WorkStartTypeName)
                    </td>
                    <td>
                        @Html.DisplayFor(m => m.RoundingList[i].WorkEndTypeName)
                    </td>
                    <td>
                        @Html.DisplayFor(m => m.RoundingList[i].LunchStartTypeName)
                    </td>
                    <td>
                        @Html.DisplayFor(m => m.RoundingList[i].LunchEndTypeName)
                    </td>
                    <td>
                        @Html.DisplayFor(m => m.RoundingList[i].BreakStartTypeName)
                    </td>
                    <td>
                        @Html.DisplayFor(m => m.RoundingList[i].BreakEndTypeName)
                    </td>
                </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <td colspan="8">
                    <div class="pagination pagination-centered hide-if-no-paging"></div>
                </td>
            </tr>
        </tfoot>
    </table>
</div>


<script type="text/javascript">
    $(document).ready(function () {
        var resultingSiteview = "<h1>Rounding <small>Rounding List </small></h1><ol class=" + '"breadcrumb"' + "><li><a href=" + '"../Home/EmployeeDashboard"' + "><i class=" + '"fa fa-dashboard"' + "></i>Home</a></li><li class=" + '"active"' + ">Rounding</li></ol>";
        $("#header-section").empty();
        $("#header-section").html(resultingSiteview);
    });
</script>

<script type="text/javascript">
    $(document).ready(function () {

        $("#btnDelete").click(function (e) {
            e.preventDefault();
            e.stopPropagation();
            var baseurl = '@System.Configuration.ConfigurationManager.AppSettings["BaseURL"]';
            var searchIDs = $("#RoundingGridContent input:checkbox:checked").map(function () {
                return $(this).attr("data-val-1");
            }).get();

            $.ajax({
                url: baseurl + "Rounding/DeleteRoundingDetail",
                type: "POST",
                cache: "false",
                data: { RoundingIds: searchIDs.toString() },
                success: function (data) {
                    if (data == "True") {
                        window.location.href = window.location.href;
                    }

                },
                error: function (request, status, error) {
                   alert(request.responseText);
                }
            });
        });

    });
</script>