PsplGenericSystem/Extensions/HRMS.Web/Areas/JobPortal/Controllers/JobPortalController.cs
using System.Globalization;
using System.IO;
using System.Text;
using System.Web.Security;
using HRMS.Common.Enums;
using HRMS.Common.Helpers;
using HRMS.Service.Interfaces;
using HRMS.Service.Models.EDM;
using HRMS.Web.Helper;
using HRMS.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net;
using System.Net.Sockets;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using iTextSharp.text.pdf;
using Newtonsoft.Json;


namespace HRMS.Web.Areas.JobPortal.Controllers
{

    public class JobPortalController : Controller
    {
        #region Class Level Variables and constructor

        private readonly IJobProfileRepository _jobProfileRepository;
        private readonly IFilesDBRepository _filesDBRepository;
        private readonly IUtilityRepository _utilityRepository;
        private readonly ICompanyRepository _companyRepository;
        private readonly IJobApplicantRepository _jobApplicantRepository;
        private readonly ICertificationandLicenseRepository _certificationandLicenseRepository;
        private readonly IUserRepository _userRepository;

        public JobPortalController(IJobProfileRepository jobProfileRepository, IFilesDBRepository filesDBRepository,
            IUtilityRepository utilityRepository, ICompanyRepository companyRepository,
            IJobApplicantRepository jobApplicantRepository,
            ICertificationandLicenseRepository certificationandLicenseRepository)
        {
            _jobProfileRepository = jobProfileRepository;
            _filesDBRepository = filesDBRepository;
            _utilityRepository = utilityRepository;
            _companyRepository = companyRepository;
            _jobApplicantRepository = jobApplicantRepository;
            _certificationandLicenseRepository = certificationandLicenseRepository;

        }

        #endregion

        /// <summary>
        /// To show all the available jobs in a company
        /// </summary>
        /// <returns></returns>
        public ActionResult AvailableJobs()
        {

            var availableJobFormModelObj = new AvailableJobFormModel();
            if ((string.IsNullOrEmpty(GlobalsVariables.CurrentCompanyId)) && (Request.QueryString["CompanyId"] != null) ||
                (Request.QueryString["CompanyId"] != GlobalsVariables.CurrentCompanyId))
            {
                //Session.Abandon();
                //Session.Clear();
                int companyId = Convert.ToInt32(Request.QueryString["CompanyId"]);
                if (companyId != 0)
                    GlobalsVariables.CurrentCompanyId = Convert.ToString(companyId);
            }
            var companyInfoObj =
                _companyRepository.GetEditCompanyInfo(Convert.ToInt32(GlobalsVariables.CurrentCompanyId));
            GlobalsVariables.CurrentCompanyName = companyInfoObj.CompanyName;
            var lstlookup = _utilityRepository.GetLookUpData(Convert.ToInt32(GlobalsVariables.CurrentCompanyId));
            availableJobFormModelObj.Jobs =
                _jobProfileRepository.ListAvailableJobsForJobPortal(Convert.ToInt32(GlobalsVariables.CurrentCompanyId));
            availableJobFormModelObj.JobCategoryList =
                lstlookup.Where(j => j.TableName == LocalizedStrings.JobCategory).ToList();


            if (!string.IsNullOrEmpty(GlobalsVariables.CurrentUserId))
            {
                var listappliedjobs =
                    _jobApplicantRepository.AppliedJobs(Convert.ToInt32(GlobalsVariables.CurrentUserId));
                if (listappliedjobs.Count > 0 && listappliedjobs[0] != null)
                    availableJobFormModelObj.Jobs = (from jobprofiles in availableJobFormModelObj.Jobs
                                                     where listappliedjobs.All(appliedjob => appliedjob.JobProfileId != jobprofiles.JobProfileId)
                                                     select jobprofiles).ToList();
            }

            foreach (var jobprofile in availableJobFormModelObj.Jobs)
            {
                var jobDuties = _jobProfileRepository.ListJobDutiesInJobProfile(jobprofile.JobProfileId);

                foreach (var jobduty in jobDuties)
                {
                    var selectedJobPropertyObj = new SelectedJobProperty();
                    selectedJobPropertyObj.Id = jobduty.JobDutyId;
                    selectedJobPropertyObj.Property = GeneralEnum.JobProperties.JobDuty.ToString();
                    selectedJobPropertyObj.Description = jobduty.Description;
                    selectedJobPropertyObj.JobProfileId = jobprofile.JobProfileId;
                    selectedJobPropertyObj.PercentageOfTime = jobduty.PercentageOfTime;
                    availableJobFormModelObj.SelectedJobProperties.Add(selectedJobPropertyObj);
                }

                var jobQualifications = _jobProfileRepository.ListJobQualificationsInJobProfile(jobprofile.JobProfileId);
                foreach (var jobqualification in jobQualifications)
                {

                    var selectedJobPropertyObj = new SelectedJobProperty();
                    selectedJobPropertyObj.Id = jobqualification.JobQualificationId;
                    selectedJobPropertyObj.Property = GeneralEnum.JobProperties.JobQualification.ToString();
                    selectedJobPropertyObj.Description = jobqualification.Description;
                    selectedJobPropertyObj.JobProfileId = jobprofile.JobProfileId;
                    selectedJobPropertyObj.Proficiency = jobqualification.Proficiency;
                    availableJobFormModelObj.SelectedJobProperties.Add(selectedJobPropertyObj);
                }

                var jobPMEs = _jobProfileRepository.ListJobPMEsInJobProfile(jobprofile.JobProfileId);
                foreach (var jobpme in jobPMEs)
                {
                    var selectedJobPropertyObj = new SelectedJobProperty();
                    selectedJobPropertyObj.Id = jobpme.PMEId;
                    selectedJobPropertyObj.Property = GeneralEnum.JobProperties.JobPME.ToString();
                    selectedJobPropertyObj.Description = jobpme.Description;
                    selectedJobPropertyObj.JobProfileId = jobprofile.JobProfileId;
                    availableJobFormModelObj.SelectedJobProperties.Add(selectedJobPropertyObj);
                }
            }


            //availableJobFormModelObj.JobQualifications = _jobProfileRepository.ListJobQualificationsInJobProfile(Convert.ToInt32(GlobalsVariables.CurrentCompanyId));
            //availableJobFormModelObj.JobPmes = _jobProfileRepository.ListJobPMEsInJobProfile(Convert.ToInt32(GlobalsVariables.CurrentCompanyId));
            return View(availableJobFormModelObj);
        }

        /// <summary>
        /// To show available jobs in a company
        /// </summary>
        /// <param name="availableJobFormModelObj"></param>
        /// <param name="command"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult AvailableJobs(AvailableJobFormModel availableJobFormModelObj, string command)
        {
            var lstlookup = _utilityRepository.GetLookUpData(Convert.ToInt32(GlobalsVariables.CurrentCompanyId));
            availableJobFormModelObj.Jobs =
                _jobProfileRepository.ListAvailableJobsForJobPortal(Convert.ToInt32(GlobalsVariables.CurrentCompanyId));
            availableJobFormModelObj.JobCategoryList =
                lstlookup.Where(j => j.TableName == LocalizedStrings.JobCategory).ToList();


            availableJobFormModelObj.Jobs =
                availableJobFormModelObj.Jobs.Where(p => p.JobCategory == availableJobFormModelObj.JobCategory).ToList();

            foreach (var jobprofileObj in availableJobFormModelObj.Jobs)
            {

                var jobDuties = _jobProfileRepository.ListJobDutiesInJobProfile(jobprofileObj.JobProfileId);
                foreach (var jobduty in jobDuties)
                {
                    var selectedJobPropertyObj = new SelectedJobProperty();
                    selectedJobPropertyObj.Id = jobduty.JobDutyId;
                    selectedJobPropertyObj.Property = GeneralEnum.JobProperties.JobDuty.ToString();
                    selectedJobPropertyObj.Description = jobduty.Description;
                    selectedJobPropertyObj.JobProfileId = jobprofileObj.JobProfileId;
                    selectedJobPropertyObj.PercentageOfTime = jobduty.PercentageOfTime;
                    availableJobFormModelObj.SelectedJobProperties.Add(selectedJobPropertyObj);
                }
                var jobQualifications =
                    _jobProfileRepository.ListJobQualificationsInJobProfile(jobprofileObj.JobProfileId);
                foreach (var jobqualification in jobQualifications)
                {

                    var selectedJobPropertyObj = new SelectedJobProperty();
                    selectedJobPropertyObj.Id = jobqualification.JobQualificationId;
                    selectedJobPropertyObj.Property = GeneralEnum.JobProperties.JobQualification.ToString();
                    selectedJobPropertyObj.Description = jobqualification.Description;
                    selectedJobPropertyObj.JobProfileId = jobprofileObj.JobProfileId;
                    selectedJobPropertyObj.Proficiency = jobqualification.Proficiency;
                    availableJobFormModelObj.SelectedJobProperties.Add(selectedJobPropertyObj);
                }

                var jobPMEs = _jobProfileRepository.ListJobPMEsInJobProfile(jobprofileObj.JobProfileId);
                foreach (var jobpme in jobPMEs)
                {
                    var selectedJobPropertyObj = new SelectedJobProperty();
                    selectedJobPropertyObj.Id = jobpme.PMEId;
                    selectedJobPropertyObj.Property = GeneralEnum.JobProperties.JobPME.ToString();
                    selectedJobPropertyObj.Description = jobpme.Description;

PsplGenericSystem/Extensions/HRMS.Web/Areas/JobPortal/Views/JobPortal/AddCertificationLicence.cshtml
@model HRMS.Web.ViewModels.CertificationandLicenseFormModel
@using System.Web.Optimization;
@using HRMS.Common.Helpers;
@using HRMS.Web.Models;
@{
    ViewBag.Title = "AddCertificationLicence";
    Layout = "~/Areas/JobPortal/Views/Shared/_JobPortalMaster.cshtml";
}

<h3>Certification Licence</h3>
@using (Html.BeginForm("AddCertificationLicence", "JobPortal", FormMethod.Post))
{
    <div class="form-horizontal">
        <div class="form-group">
            <div class="col-md-6">
                <div class="form-group">
                    @Html.HiddenFor(k => k.CertificationandLicense.CertificationLicensesId)
                    @Html.HiddenFor(k => k.CertificationandLicense.CompanyId)
                    @Html.HiddenFor(k => k.CertificationandLicense.UserId)
                    @Html.LabelFor(m => m.CertificationandLicense.Name, new { @class = "col-sm-3 control-label required" })
                    <div class="col-sm-9">
                        @Html.TextBoxFor(k => k.CertificationandLicense.Name, new { @class = "form-control" })
                    </div>
                </div>             
                <div class="form-group">
                    @Html.LabelFor(k => k.CertificationandLicense.IssueDate, new { @class = "col-sm-3 control-label " })
                    <div class="col-sm-9">
                        <div class="input-group">
                            @Html.TextBoxFor(k => k.CertificationandLicense.IssueDate, (Model.CertificationandLicense.IssueDate == null ? "" : ((DateTime)Model.CertificationandLicense.IssueDate).ToString("MM/dd/yyyy")), new { @class = "form-control dateControl", @id = "txtissuedate", @maxlength = 10 })
                            <label for="txtissuedate" class="input-group-addon">
                                <span class="glyphicon glyphicon-calendar"></span>
                            </label>
                        </div>
                    </div>
                </div>                     
                <div class="form-group">
                    @Html.LabelFor(k => k.CertificationandLicense.RenewalDate, new { @class = "col-sm-3 control-label " })
                    <div class="col-sm-9">
                        <div class="input-group">
                            @Html.TextBoxFor(k => k.CertificationandLicense.RenewalDate, (Model.CertificationandLicense.RenewalDate == null ? "" : ((DateTime)Model.CertificationandLicense.RenewalDate).ToString("MM/dd/yyyy")), new { @class = "form-control dateControl", @id = "txtrenvaldate", @maxlength = 10 })
                            <label for="txtrenvaldate" class="input-group-addon">
                                <span class="glyphicon glyphicon-calendar"></span>
                            </label>
                        </div>
                    </div>
                </div>  
                <div class="form-group">
                    @Html.LabelFor(k => k.CertificationandLicense.ExpirationDate, new { @class = "col-sm-3 control-label " })
                    <div class="col-sm-9">
                        <div class="input-group">
                            @Html.TextBoxFor(m => m.CertificationandLicense.ExpirationDate, (Model.CertificationandLicense.ExpirationDate == null ? "" : ((DateTime)Model.CertificationandLicense.ExpirationDate).ToString("MM/dd/yyyy")), new { @class = "form-control dateControl", @id = "txtexpirydate", @maxlength = 10 })
                            <label for="txtexpirydate" class="input-group-addon">
                                <span class="glyphicon glyphicon-calendar"></span>
                            </label>
                        </div>
                    </div>
                </div>  

            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 control-button">
            <button type="submit" class="btn btn-success">Save</button>
            @Html.ActionLink("Cancel", "AddApplicationInfo", null, new { @class = "btn btn-success" })
        </div>
    </div>
}

PsplGenericSystem/Extensions/HRMS.Web/Areas/JobPortal/Views/JobPortal/AddEducationInfo.cshtml
@model HRMS.Service.Models.EDM.ApplicantEducation
@{
    ViewBag.Title = "AddEducationInfo";
    Layout = "~/Areas/JobPortal/Views/Shared/_JobPortalMaster.cshtml";
}

<h3>Education Info</h3>
@using (Html.BeginForm("AddEducationInfo", "JobPortal", FormMethod.Post))
{
    <div class="form-horizontal">
        <div class="form-group">
            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(k => k.University, new { @class = "col-sm-3 control-label required" })
                    <div class="col-sm-9">
                        @Html.TextBoxFor(k => k.University, new { @class = "form-control required" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(k => k.Degree, new { @class = "col-sm-3 control-label required" })
                    <div class="col-sm-9">
                        @Html.TextBoxFor(k => k.Degree, new { @class = "form-control required" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(k => k.FromDate, new { @class = "col-sm-3 control-label " })
                    <div class="col-sm-9">
                        <div class="input-group">
                            @Html.TextBoxFor(m => m.FromDate, (Model.FromDate == null ? "" : ((DateTime)Model.FromDate).ToString("MM/dd/yyyy")), new { @class = "form-control dateControl", @id = "txtfromdate", @maxlength = 10 })
                            <label for="txtfromdate" class="input-group-addon">
                                <span class="glyphicon glyphicon-calendar"></span>
                            </label>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.ToDate, new { @class = "col-sm-3 control-label " })
                    <div class="col-sm-9">
                        <div class="input-group">
                            @Html.TextBoxFor(m => m.ToDate, (Model.ToDate == null ? "" : ((DateTime)Model.ToDate).ToString("MM/dd/yyyy")), new { @class = "form-control dateControl", @id = "txttodate" })
                            <label for="txttodate" class="input-group-addon">
                                <span class="glyphicon glyphicon-calendar"></span>
                            </label>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(k => k.Activities, new { @class = "col-sm-3 control-label" })
                    <div class="col-sm-9">
                        @Html.TextBoxFor(k => k.Activities, new { @class = "form-control" })
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 control-button">
            <button type="submit" class="btn btn-success">Save</button>
            @Html.ActionLink("Cancel", "AddApplicationInfo", null, new { @class = "btn btn-success" })
        </div>
    </div>
}

PsplGenericSystem/Extensions/HRMS.Web/Areas/JobPortal/Views/JobPortal/AddEmploymentInfo.cshtml
@model HRMS.Service.Models.EDM.ApplicantEmploymentHistory
@{
    ViewBag.Title = "AddEmploymentInfo";
   Layout = "~/Areas/JobPortal/Views/Shared/_JobPortalMaster.cshtml";
}

<h3>Employment Info</h3>
@using (Html.BeginForm("AddEmploymentInfo", "JobPortal", FormMethod.Post))
{
    <div class="form-horizontal">
        <div class="form-group">
            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(k => k.Title, new { @class = "col-sm-3 control-label required" })
                    <div class="col-sm-9">
                        @Html.TextBoxFor(k => k.Title, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(k => k.Description, new { @class = "col-sm-3 control-label " })
                    <div class="col-sm-9">
                        @Html.TextAreaFor(k => k.Description, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(k => k.Location, new { @class = "col-sm-3 control-label " })
                    <div class="col-sm-9">
                        @Html.TextBoxFor(k => k.Location, new { @class = "form-control" })
                    </div>
                </div>
               
                <div class="form-group">
                    @Html.LabelFor(k => k.EmploymentStartDate, new { @class = "col-sm-3 control-label " })
                    <div class="col-sm-9">
                        <div class="input-group">
                            @Html.TextBoxFor(m => m.EmploymentStartDate, (Model.EmploymentStartDate == null ? "" : ((DateTime)Model.EmploymentStartDate).ToString("MM/dd/yyyy")), new { @class = "form-control dateControl", @id = "txtstartdate", @maxlength = 10 })
                            <label for="txtstartdate" class="input-group-addon">
                                <span class="glyphicon glyphicon-calendar"></span>
                            </label>
                        </div>
                    </div>
                </div>   
                <div class="form-group">
                    @Html.LabelFor(k => k.EmploymentEndDate, new { @class = "col-sm-3 control-label " })
                    <div class="col-sm-9">
                        <div class="input-group">
                            @Html.TextBoxFor(m => m.EmploymentEndDate, (Model.EmploymentEndDate == null ? "" : ((DateTime)Model.EmploymentEndDate).ToString("MM/dd/yyyy")), new { @class = "form-control dateControl", @id = "txtenddate", @maxlength = 10 })
                            <label for="txtenddate" class="input-group-addon">
                                <span class="glyphicon glyphicon-calendar"></span>
                            </label>
                        </div>
                    </div>
                </div>
               
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 control-button">
            <button type="submit" class="btn btn-success">Save</button>
            @Html.ActionLink("Cancel", "AddApplicationInfo", null, new { @class = "btn btn-success" })
        </div>
    </div>
}

PsplGenericSystem/Extensions/HRMS.Web/Areas/JobPortal/Views/JobPortal/AddSkillInfo.cshtml
@model HRMS.Service.Models.EDM.ApplicantAchievementsAndAssociations
@{
    ViewBag.Title = "AddSkillInfo";
     Layout = "~/Areas/JobPortal/Views/Shared/_JobPortalMaster.cshtml";
}

<h3>AddSkillInfo</h3>
@using (Html.BeginForm("AddSkillInfo", "JobPortal", FormMethod.Post))
{
    <div class="form-horizontal"> 
        <div class="form-group">
            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(k => k.Type, new { @class = "col-sm-3 control-label required" })
                    <div class="col-sm-9">
                        @Html.TextBoxFor(k => k.Type, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(k => k.Description, new { @class = "col-sm-3 control-label " })
                    <div class="col-sm-9">
                        @Html.TextBoxFor(k => k.Description, new { @class = "form-control" })
                    </div>
                </div>
                

            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 control-button">
            <button type="submit" class="btn btn-success">Save</button>
            @Html.ActionLink("Cancel", "AddApplicationInfo", null, new { @class = "btn btn-success" })
        </div>
    </div>
}

PsplGenericSystem/Extensions/HRMS.Web/Areas/JobPortal/Views/JobPortal/AppliedJobs.cshtml
@model IList<HRMS.Web.ViewModels.AppliedJobsFormModel>
@using HRMS.Common.Enums;
@{
    ViewBag.Title = "AppliedJobs";
    Layout = "~/Areas/JobPortal/Views/Shared/_JobPortalMaster.cshtml";
}

<h2>AppliedJobs</h2>


<div id="gridContent" style="padding-top: 10px;">
    <table class="footable table" data-filter="#filter" data-page-size="5" data-page-previous-text="prev" data-page-next-text="next" id="appliedJobsGridContent">
        <thead>
            <tr>
                <th data-toggle="true">
                    @Html.DisplayName("Job Title")
                </th>
                <th data-hide="phone">
                    @Html.DisplayName("Job Applied On")
                </th>
                <th data-hide="phone">
                    @Html.DisplayName("Job Location")
                </th>
                <th data-hide="phone,tablet">
                    @Html.DisplayName("Status")
                </th>
            </tr>
        </thead>
        <tbody>
            @for (var i = 0; i < Model.Count; i++)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => modelItem[i].JobTitle)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => modelItem[i].JobAppliedOn)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => modelItem[i].JobLocation)
                    </td>
                    @*<td>
                            @Html.DisplayFor(modelItem => modelItem[i].JobStatus)
                        </td>*@
                    <td>
                        @{
                         var jobAppliedStatus = @Model[i].JobStatus;
                        }
                        @if (jobAppliedStatus != null)
                        {
                            @Html.Label(((GeneralEnum.JobApplicationStatus)@Model[i].JobStatus).ToString())
                        }
                    </td>

                </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <td colspan="8">
                    <div class="pagination pagination-centered hide-if-no-paging"></div>
                </td>
            </tr>
        </tfoot>
    </table>
</div>

@*<script type="text/javascript">
    $(document).ready(function () {
        $("#lbljobcount")[0].textContent = '@Model.Jobs.Count()';

    });
    </script>*@

PsplGenericSystem/Extensions/HRMS.Web/Areas/JobPortal/Views/JobPortal/UpdateEducationInfo.cshtml
@model HRMS.Service.Models.EDM.ApplicantEducation
@{
    ViewBag.Title = "AddEducationInfo";
    Layout = "~/Areas/JobPortal/Views/Shared/_JobPortalMaster.cshtml";
}

<h3>Education Info</h3>
@using (Html.BeginForm("UpdateEducationInfo", "JobPortal", FormMethod.Post))
{
    <div class="form-horizontal">
        <div class="form-group">
            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(k => k.University, new { @class = "col-sm-3 control-label required" })
                    <div class="col-sm-9">
                        @Html.TextBoxFor(k => k.University, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(k => k.Degree, new { @class = "col-sm-3 control-label " })
                    <div class="col-sm-9">
                        @Html.TextBoxFor(k => k.Degree, new { @class = "form-control" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(k => k.FromDate, new { @class = "col-sm-3 control-label " })
                    <div class="col-sm-9">
                        <div class="input-group">
                            @Html.TextBoxFor(m => m.FromDate, (Model.FromDate == null ? "" : ((DateTime)Model.FromDate).ToString("MM/dd/yyyy")), new { @class = "form-control dateControl", @id = "txtfromdate", @maxlength = 10 })
                            <label for="txtfromdate" class="input-group-addon">
                                <span class="glyphicon glyphicon-calendar"></span>
                            </label>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.ToDate, new { @class = "col-sm-3 control-label " })
                    <div class="col-sm-9">
                        <div class="input-group">
                            @Html.TextBoxFor(m => m.ToDate, (Model.ToDate == null ? "" : ((DateTime)Model.ToDate).ToString("MM/dd/yyyy")), new { @class = "form-control dateControl", @id = "txttodate" })
                            <label for="txttodate" class="input-group-addon">
                                <span class="glyphicon glyphicon-calendar"></span>
                            </label>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(k => k.Activities, new { @class = "col-sm-3 control-label" })
                    <div class="col-sm-9">
                        @Html.TextBoxFor(k => k.Activities, new { @class = "form-control" })
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 control-button">
            <button type="submit" class="btn btn-success">Save</button>
            @Html.ActionLink("Cancel", "AddApplicationInfo", null, new { @class = "btn btn-success" })
        </div>
    </div>
}

PsplGenericSystem/Extensions/HRMS.Web/Areas/JobPortal/Views/JobPortal/_AddEducationInfo.cshtml
@{
    ViewBag.Title = "_AddEducationInfo";
    Layout = "~/Areas/JobPortal/Views/Shared/_JobPortalMaster.cshtml";
}
<h3>EducationInfo</h3>
@using (Html.BeginForm("_AddEducationInfo", "JobPortal", FormMethod.Post))
{
    <div class="form-horizontal">
        <div class="form-group">
            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(k => k.ApplicantEducation.University, new { @class = "col-sm-3 control-label required" })
                    <div class="col-sm-9">
                        @Html.TextBoxFor(k => k.ApplicantEducation.University, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(k => k.ApplicantEducation.Degree, new { @class = "col-sm-3 control-label " })
                    <div class="col-sm-9">
                        @Html.TextBoxFor(k => k.ApplicantEducation.Degree, new { @class = "form-control" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(k => k.ApplicantEducation.FromDate, new { @class = "col-sm-3 control-label " })
                    <div class="col-sm-9">
                        <div class="input-group">
                            @Html.TextBoxFor(m => m.ApplicantEducation.FromDate, (Model.ApplicantEducation.FromDate == null ? "" : ((DateTime)Model.ApplicantEducation.FromDate).ToString("MM/dd/yyyy")), new { @class = "form-control dateControl", @id = "txtfromdate", @maxlength = 10 })
                            <label for="txtfromdate" class="input-group-addon btn">
                                <span class="glyphicon glyphicon-calendar"></span>
                            </label>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.ApplicantEducation.ToDate, new { @class = "col-sm-3 control-label " })
                    <div class="col-sm-9">
                        <div class="input-group">
                            @Html.TextBoxFor(m => m.ApplicantEducation.ToDate, (Model.ApplicantEducation.ToDate == null ? "" : ((DateTime)Model.ApplicantEducation.ToDate).ToString("MM/dd/yyyy")), new { @class = "form-control dateControl", @id = "txttodate" })
                            <label for="txttodate" class="input-group-addon btn">
                                <span class="glyphicon glyphicon-calendar"></span>
                            </label>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(k => k.ApplicantEducation.Activities, new { @class = "col-sm-3 control-label" })
                    <div class="col-sm-9">
                        @Html.TextBoxFor(k => k.ApplicantEducation.Activities, new { @class = "form-control" })
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 control-button">
            <button type="submit" class="btn btn-success">Save</button>
            @Html.ActionLink("Cancel", "AddApplicationInfo", null, new { @class = "btn btn-success" })
        </div>
    </div>
}